# Schema for the configuration files of the Elf module.

elf.settings:
  type: config_object
  label: 'Elf settings'
  mapping:
    elf_domains:
      label: 'Internal domains'
      type: sequence
      sequence:
        type: string
    elf_window:
      type: boolean
      label: 'Use JavaScript to open external links in a new window'
    elf_redirect:
      type: boolean
      label: 'Redirect users to external websites via !url_path'
