<?php
/**
 * @file
 * PNWDS Attendee module.
 */

/**
 * Implements hook_entity_update().
 */
function pnwds_attendees_entity_update($entity, $type) {

  // Ticket Status is complete. Set user as an attendee.
  if ($type == 'ticket_registration') {
    $ticket_state = entity_metadata_wrapper('ticket_registration', $entity)->ticket_state->raw();
    $completed_state = entity_metadata_wrapper('ticket_type', $entity->ticket_type())->field_complete_state->raw();

    // Status has changed and the new status is complete.
    if ($entity->original->ticket_state != $entity->ticket_state && $ticket_state == $completed_state) {
      $user = user_load($entity->user_uid);
      $user_wrapper = entity_metadata_wrapper('user', $user);

      // Using variable get here, even though we con't have a variable because
      // eventually we'll want an admin interface to set it.
      $user_wrapper->roles[] = variable_get('pnwds_attendees_role', '31');
      $user_wrapper->save();
    }
  }
}
