<?php
/**
 * @file
 * PNWDS Attendee module.
 */

/**
 * Implements hook_entity_update().
 *
 * If the ticket state is target id is 31, it is complete. So, set the user to an attendee role.
 */
function pnwds_attendees_entity_update($entity, $type) {

  // If ticket status is complete. Set user as an attendee role
  if ($type == 'ticket_registration' && !empty($entity->ticket_state)) {
    $ts = ticket_state_load($entity->ticket_state[LANGUAGE_NONE][0]['target_id']);
    if($ts->name == 'completed') {
      $user = user_load($entity->user_uid);
      $user_wrapper = entity_metadata_wrapper('user', $user);

      // 31 is the role id for attendees
      $user_wrapper->roles[]= '31';
      $user_wrapper->save();
    }
  }
}
