<?php

/**
 * @file
 * Contains conference.page.inc.
 *
 * Page callback for Conference entities.
 */

use Drupal\Core\Render\Element;

/**
 * Prepares variables for Conference templates.
 *
 * Default template: conference.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the user information and any
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_conference(array &$variables) {
}
