name = PNWDS - Main Layout
description = A region layout with zone-esque wrappers.
preview = preview.png
template = wrappers

; Regions
regions[navigation]     = Navigation bar
regions[header]         = Header
regions[branding]       = Branding
regions[menu]           = Main Menu
regions[highlighted]    = Highlighted
regions[help]           = Help
regions[preface]        = Preface
regions[content]        = Content
regions[sidebar_first]  = First sidebar
regions[sidebar_second] = Second sidebar
regions[postscript]     = Postscript
regions[footer]         = Footer

; Stylesheets
stylesheets[all][] = css/layouts/wrappers/wrappers.layout.css
