<?php
/**
 * @file
 * Code for the cod_registration feature.
 */

include_once 'cod_registration.features.inc';
include_once 'cod_registration.admin.inc';
module_load_include('admin.inc','ticket', 'includes/ticket_registration');

/*
 * COD Registration initial page
 */
function cod_registration_menu() {

  if(variable_get('cod_registration_display_page', FALSE) && variable_get('cod_events_default_event', FALSE)) {
    $items['register'] = array(
      'title'             => 'Registration',
      'access callback'   => 'cod_registration_reg_perms',
      'page callback'     => 'drupal_get_form',
      'page arguments'    => array('cod_registration_wizard', variable_get('cod_events_default_event', FALSE)),
      'type'              => MENU_CALLBACK,
    );
  }

  $items['node/%node/tickets/checkin/%'] = array(
    'title'             => 'Registration',
    'access callback'   => 'cod_registration_reg_perms',
    'page callback'     => 'drupal_get_form',
    'page arguments'    => array('cod_registration_checkin', 1,4),
    'type'              => MENU_CALLBACK,
  );

  return $items;
}

/*
 * TODO: Make this secure.
 */
function cod_registration_reg_perms($uid = NULL) {
  return TRUE;
}

/**
 * Implements hook_system_info_alter().
 */
function cod_registration_system_info_alter(&$info, $file, $type) {
 // Only include the mobile codes feature if the module is enabled
  if ($file->name == 'cod_registration' && module_exists('mobile_codes')) {
    $info['features']['mobile_codes_presets'][] = 'cod_registration_qrcode';
  }
}

/*
 * Registration Checkin Page. Marks the user as checked in and prints a badge if they want.
 */
function cod_registration_checkin($form, &$form_state, $group, $ticket_id) {
  global $user;
  module_load_include('inc', 'cod_registration', 'cod_registration.print');

  // Who performed the check-in?
  $registrar = $user->uid;
  $ticket_data = ticket_registration_load($ticket_id);

  $form = drupal_get_form('ticket_registration_form', $ticket_data, 'edit');

  $form['checkin'] = array(
    '#markup' => t('Almost checked-in, please select which item you wish to check in for'),
  );
  $form['field_event'] = array(
    '#type' => 'value',
    '#value' => $group->nid,
  );

  $voc = taxonomy_vocabulary_machine_name_load('checkin_types');
  $tree = taxonomy_get_tree($voc->vid);
  $options = array('_none' => t('- None -'));
  foreach($tree as $term) {
    $options[$term->tid] = $term->name;
  }
  $form['field_checkin_type'] = array(
    '#type' => 'select',
    '#options' => $options,
    '#default_value' => 862,
    '#value_key' => 'tid',
    '#weight' => 100,
  );

  $form['field_ticket_registration'] = array(
    '#type' => 'value',
    '#value' => $ticket_id,
  );

  $form['field_checkin_registrar'] = array(
    '#type' => 'value',
    '#value' => $registrar,
  );

  $form['print'] = array(
    '#type' => 'submit',
    '#value' => t('Print Badge'),
    '#submit' => array('cod_registration_checkin_submit', 'cod_registration_confirmation_print_submit'),
    '#weight' => 101,
  );
  $form['noprint'] = array(
    '#type' => 'submit',
    '#value' => t('Check-in'),
    '#weight' => 102,
  );

  //custom submit functions for some sanity checking. Probably could use some more sanity
  //nothing we really need to validate at this point
  $form['#submit'][] = 'cod_registration_checkin_submit';

  return $form;
}

function cod_registration_checkin_submit($form, &$form_state) {

  $ticket_data = ticket_registration_load($form_state['values']['field_ticket_registration']);
  $registered_account = user_load($ticket_data->user_uid);

  //error_log(print_r($form_state,true));
  foreach($registered_account->field_profile_checkin[LANGUAGE_NONE] AS $checkin_fields) {
    if($field_collection_item = field_collection_item_load($checkin_fields['value'])) { // Load that field collection item.
      if($field_collection_item->field_event[LANGUAGE_NONE][0]['target_id'] == $form_state['values']['field_event'] &&
         $field_collection_item->field_checkin_type[LANGUAGE_NONE][0]['tid'] ==  $form_state['values']['field_checkin_type'] &&
         $field_collection_item->field_checkin_value[LANGUAGE_NONE][0]['value'] == 1) {
         drupal_set_message("You're already checked in");
         return;
      }
    }
  }

  $values = array();
  $values['field_name'] = 'field_profile_checkin';
  $values['field_event'][LANGUAGE_NONE][0]['target_id'] = $form_state['values']['field_event'];
  $values['field_checkin_type'][LANGUAGE_NONE][0]['tid'] = $form_state['values']['field_checkin_type'];
  $values['field_checkin_value'][LANGUAGE_NONE][0]['value'] = 1;
  $values['field_checkin_registrar'][LANGUAGE_NONE][0]['target_id'] = $form_state['values']['field_checkin_registrar'];
  $values['field_checkin_time'][LANGUAGE_NONE][0]['value'] = time();

  $field_collection_item = entity_create('field_collection_item', $values);
  $field_collection_item->setHostEntity('user', $registered_account);
  $field_collection_item->save();
}

/*
 * Registration forms
 */
function cod_registration_wizard($form, &$form_state, $event_id) {
  global $user;
  $node = node_load($event_id);
  // Load the ticket module for forms

  // Initialize a description of the steps for the wizard.
  // Step 1: Show ticket information page
  // Step 1a: If already registered, show registration information
  // Step 2: Show ticket registration boxes
  // Step 3: Complete order and/or send to commerce
  if (empty($form_state['step'])) {
    //pass the login step if the user is already logged in
    if (isset($user->uid) && $user->uid > 0) {
      // We already have a username, do they have registrations?
     // if ($tickets = ticket_get_user_registrations($user, 'node', $node->nid)) {
     //   drupal_set_message(t("You're already registered for @node", array('@node' => $node->title)));
     //   drupal_goto('user/'.$user->uid.'/tickets/'.$event_id);
      //}
    }
    // This array contains the function to be called at each step to get the
    // relevant form elements. It will also store state information for each
    // step.
    $form_state['step_information'] = _cod_registration_steps();
    $form_state['step'] = 1;
  }
  $step = &$form_state['step'];

  drupal_set_title(t('@event Registration: Step @step', array('@event' => $node->title, '@step' => $step)));

  // Call the function named in $form_state['step_information'] to get the
  // form elements to display for this step.

  $form = drupal_get_form($form_state['step_information'][$step]['form'], $node);
  unset($form['submit']);

  $form['node'] = array(
    '#type' => 'value',
    '#value' => $node->nid,
  );

  // Show the 'previous' button if appropriate. Note that #submit is set to
  // a special submit handler, and that we use #limit_validation_errors to
  // skip all complaints about validation when using the back button. The
  // values entered will be discarded, but they will not be validated, which
  // would be annoying in a "back" button.
  if ($step > 1) {
    $form['prev'] = array(
      '#type' => 'submit',
      '#value' => t('Previous'),
      '#name' => 'prev',
      '#submit' => array('cod_registration_wizard_previous_submit'),
      '#limit_validation_errors' => array(),
    );
  }

  // Show the Next button only if there are more steps defined.
  if ($step < count($form_state['step_information'])) {
    // The Next button should be included on every step
    $form['next'] = array(
      '#type' => 'submit',
      '#value' => t('Next'),
      '#name' => 'next',
      '#weight' => 100,
      '#submit' => array('cod_registration_wizard_next_submit'),
    );
    $active = 'next';
  }
  else {
    // Just in case there are no more steps, we use the default submit handler
    // of the form wizard. When this button is clicked, the
    // grasmash_registration_wizard_submit handler will be called.
    $form['finish'] = array(
      '#type' => 'submit',
      '#value' => t('Complete Registration'),
      '#submit' => array('cod_registration_wizard_submit'),
      '#validate' => array('cod_registration_wizard_validate'),
    );
    $active = 'finish';
  }

  $form[$active]['#validate'] = array();
  // Include each validation function defined for the different steps.
  // First, look for functions that match the form_id_validate naming convention.
  if (function_exists($form_state['step_information'][$step]['form'] . '_validate')) {
    $form[$active]['#validate'] = array($form_state['step_information'][$step]['form'] . '_validate');
  }
  // Next, merge in any other validate functions defined by child form.
  if (isset($form['#validate'])) {
    $form[$active]['#validate'] = array_merge($form[$active]['#validate'], $form['#validate']);
    unset($form['#validate']);
  }

  // Let's do the same thing for #submit handlers.
  // First, look for functions that match the form_id_submit naming convention.
  if (function_exists($form_state['step_information'][$step]['form'] . '_submit')) {
    $form[$active]['#submit'][] = $form_state['step_information'][$step]['form'] . '_submit';
  }
  // Next, merge in any other submit functions defined by child form.
  if (isset($form['#submit'])) {
    // It's important to merge in the form-specific handlers first, before
    // grasmash_registration_wizard_next_submit clears $form_state['values].
    $form[$active]['#submit'] = array_merge($form['#submit'], $form[$active]['#submit']);
    unset($form['#submit']);
  }
  return $form;
}

// Show the registration options form
function cod_registration_options_form($form, &$form_state, $event) {
  $form = field_view_field('node', $event, 'field_event_tickets', 'ticket_type');
  // Remove the submit function in lieu of our own next button
  unset($form['submit'], $form['#submit']);
  return $form;
}

function cod_registration_options_submit(&$form, &$form_state) {
  // Collate the ticket types and quantities into an easy array.
  $build_forms = array();

  foreach ($form_state['input'] as $form_field => $value) {
    if (strpos($form_field, TICKET_QUANTITY_PREFIX) === 0 && !empty($value)) {
      $ttid = str_replace(TICKET_QUANTITY_PREFIX, '', $form_field);
      $build_forms[$ttid] = $value;
    }
  }
  if (!empty($build_forms)) {
    $_SESSION['ticket']['build_forms'] = $build_forms;
    $_SESSION['ticket']['return_url'] = current_path();
  }

  return $form;
}

function cod_registration_wizard_previous_submit($form, &$form_state) {
  $current_step = &$form_state['step'];
  $form_state['step_information'][$current_step]['stored_values'] = $form_state['values'];
  if ($current_step > 1) {
    $current_step--;
    $form_state['values'] = $form_state['step_information'][$current_step]['stored_values'];
  }
  $form_state['rebuild'] = TRUE;
}

function cod_registration_wizard_next_submit($form, &$form_state) {
  $current_step = &$form_state['step'];
  $form_state['step_information'][$current_step]['stored_values'] = $form_state['values'];

  if ($current_step < count($form_state['step_information'])) {
    $current_step++;
    if (!empty($form_state['step_information'][$current_step]['stored_values'])) {
      $form_state['values'] = $form_state['step_information'][$current_step]['stored_values'];
    }

    $form_state['rebuild'] = TRUE;  // Force rebuild with next step.
    return;
  }
}

function cod_registration_wizard_validate(&$form, &$form_state) {
  //dpm('validating');
  //dpm($form_state);
}
// And now comes the magic of the wizard, the function that should handle all the
// inputs from the user on each different step.
/**
 * Wizard form submit handler.
 * - Saves away $form_state['values']
 * - Process all the form values.
 *
 * This demonstration handler just do a drupal_set_message() with the information
 * collected on each different step of the wizard.
 *
 * @param $form
 * @param $form_state
 *
 * @ingroup form_example
 */
function cod_registration_wizard_submit($form, &$form_state) {
  //dpm($form);
  //dpm($form_state);
  drupal_set_message("Successfully Registered!");
  $current_step = &$form_state['step'];
  $form_state['step_information'][$current_step]['stored_values'] = $form_state['values'];
//  $node = node_load($form_state['values']['og_node']);
//  if(isset($form_state['values']['registration_type']) && $form_state['values']['registration_type'] == 'sponsored') {
//    drupal_set_message(t("Successfully registered for @node. Please continue checking out to be an individual sponsor", array("@node" => $node->title)));
//    cod_registration_add_to_cart($form_state['values']['uid'], $form_state);
//  }
//  else {
//    drupal_set_message(t("Successfully registered for @node!", array("@node" => $node->title)));
//    if($form_state['values']['checkin'] == 1) {
//      $form_state['redirect'] = 'node/'.$group_node->nid.'/checkin/'.$account->uid;
//    }
//  }
}

function _cod_registration_steps() {
  return array(
      1 => array(
        'form' => 'cod_registration_options_form',
      ),
      2 => array(
        'form' => 'ticket_register_form',
      ),
    );
}

/*
 * Blocks!
*/
function cod_registration_block_info() {
  // set up an empty array which will contain the block contents
  $blocks = array();

  // Generate listing of blocks from this module, for the admin/block page
  $blocks['cod_registration_link'] = array(
    'info' => t('Registration')
  );

  // return the built content
  return $blocks;
}

/**
* Implement hook_block_view()
*
* Generate HTML for the user_role_summary block
* @param op the operation from the URL
* @param delta offset
* @returns block HTML
*/
function cod_registration_block_view($delta) {
  // set up an empty array which will contain the block contents
  $block = array();
  switch($delta) {
    case 'cod_registration_link':
      $block['content'] = theme('cod_registration_link');
      // Generate our block content
      $block['subject'] = "";

      break;
  }
    // return the built content
  return $block;
}

function cod_registration_theme() {
  return array (
    'cod_registration_link' => array(),
    'cod_registration_pdf' => array(
      'variables' => array('content' => NULL),
      'template' => 'cod-registration-pdf',
    ),
  );
}

function theme_cod_registration_link() {
  global $user;

  if (isset($user->uid) && $user->uid != 0 && $registrations = ticket_get_user_registrations($user, 'node', variable_get('cod_events_default_event', FALSE))) {
      $string = 'You are registered';
  }
  else {
      $string = 'Register now';
      $reg_path = '2014';
      $class = 'register-now';
  }

  if(isset($reg_path)) {
    return l($string,$reg_path,array('attributes' => array('class' => array($class))));
  } else {
    return $string;
  }
}

function cod_registration_get_vcard($registration) {
  $vcard = _vcard_init();
  $vcard->addParam('ENCODING', '8BIT');

  if (isset($registration->field_profile_first[LANGUAGE_NONE][0]) || $registration->field_profile_last[LANGUAGE_NONE][0]) {
    $vcard->setName($registration->field_profile_last[LANGUAGE_NONE][0]['safe_value'], $registration->field_profile_first[LANGUAGE_NONE][0]['safe_value'], '', '', '');
    $vcard->addParam('ENCODING', '8BIT');
    $vcard->setFormattedName($registration->field_profile_first[LANGUAGE_NONE][0]['safe_value'] . ' ' . $registration->field_profile_last[LANGUAGE_NONE][0]['safe_value']);
    $vcard->addParam('ENCODING', '8BIT');
  }

  if ($registered_account = user_load($registration->user_uid)) {
    $vcard->addEmail(check_plain($registered_account->mail));
    $vcard->addParam('ENCODING', '8BIT');
  }

  // Organization
  if (isset($registration->field_profile_org[LANGUAGE_NONE][0])) {
    $vcard->addOrganization($registration->field_profile_org[LANGUAGE_NONE][0]['safe_value']);
    $vcard->addParam('ENCODING', '8BIT');
  }

  // Organization
  if (isset($registration->field_profile_job_title[LANGUAGE_NONE][0])) {
    $vcard->setTitle($registration->field_profile_job_title[LANGUAGE_NONE][0]['safe_value']);
    $vcard->addParam('ENCODING', '8BIT');
  }

  return $vcard;
}